apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  template:
    spec:
      containers:
        - name: guestbook
          env:
            - name: APP_MESSAGE
              value: "Siema! Tu STAGE guestbook!"
