apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/klysiak/gitops-demo
    targetRevision: main
    path: apps/nginx-helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

